#!/bin/bash
#aipupgrade is a script that removes the submissionDocumentation directory, removes DSStore files, asks and logs package type, and creates new metadata.

SCRIPTDIR=$(dirname $(which "${0}"))
. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};

_report -d "Select a package type:"
PS3="Selection? "
select PACKAGETYPE in "Production" "Preservation-Video" "Preservation-Document" "Preservation-Audio" "Unedited"
do
    break
done
echo "You've selected ${PACKAGETYPE} as your package type."

while [ "${*}" != "" ] ; do
    echo "Now I'm removing the SubmissionDocumentation directory and .DSStore files."
    INPUT="${1}"
    echo "The input is ${INPUT}"
    SUBDOC="${INPUT}/metadata/submissionDocumentation/"
    METADOC="${INPUT}/metadata/"
    echo "${METADOC}"
    shift
    "${SCRIPTDIR}/removeDSStore" "${INPUT}"
    #remove unecessary directory
    if [ -d "${SUBDOC}" ] ; then
        mv -v -n "${SUBDOC}"* "${METADOC}"
        rmdir "${SUBDOC}"
    fi
    echo "Now I'm going to create a capture log (if needed) and record the package type."
    LOGDIR="${INPUT}/metadata/logs"
    INGESTLOG="${LOGDIR}/capture.log"
    _mkdir2 "${LOGDIR}"
    echo "" >> "${INGESTLOG}"
    INGESTPACKAGETYPE=$(_readingestlog "package type")
    if [[ ! "${INGESTPACKAGETYPE}" ]] ; then
        echo "Creating capture log with package type."
        if [[ ! -f "${INGESTLOG}" ]] ; then
            _writeingestlog "made this" "aipupgrade"
        fi
        MADETHIS=$(_readingestlog "made this")
        if [[ ! "${MADETHIS}" ]] ; then
            _writeingestlog "made this" "ingestfile"
        fi
        _writeingestlog "package type" "${PACKAGETYPE}"
    fi
    "${SCRIPTDIR}/makemetadata" -r "${INPUT}"
    echo "New metadata was created for your package."
done
