#!/bin/bash
# blackatends
# Accepts one or many video files as an input and determines how many frames of black are at the beginning and at the end
scriptdir=`dirname "$0"`
. "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};

cleanup(){
    log -a "Process aborted"
    exit 1
}

trap cleanup SIGHUP SIGINT SIGTERM
log -b

[ "$#" = 0 ] && { ask_input ; once="y" ;};

while [ "$*" != ""  -o "$once" = "y" ] ; do
    once="n"
    [ "$#" != 0 ] && sourcefile="$1"
    black_at_ends "$sourcefile"
    shift
done
log -e
