#!/bin/sh

config_file="$HOME/.$(basename "${0}").conf"
touch "$config_file"
. "$config_file"

usage(){
    echo "This script will create backups of the selected database and retain the specified amount. Script can be run manually or set up as a recurring task."
    echo "Usage: -e edit configurations, -h help"
    echo "To configure either run with the -e option or open the script in a text editor to set the configuration variables."
    exit 0
}

OPTIND=1
while getopts "he" opt ; do
    case "${opt}" in
        h) usage ;;
        e) runtype="edit";;
        *)
    esac
done

_edit_config(){
    {
    echo "#Configuration Section"
    echo "#Select directory for backup"
    echo "SQL_BACKUP_DIR=\"$SQL_BACKUP_DIR\""
    echo "#Select database for backup"
    echo "DATABASE_NAME=\"$DATABASE_NAME\""
    echo "#Enter SQL log in path for database. This can be created with the command mysql_config_editor set --login-path=[name your login path here] --host=[enter database host here] --user=[enter user name here] --password"
    echo "SQL_LOGIN_PATH=\"$SQL_LOGIN_PATH\""
    echo "#Number of backup versions to retain"
    echo "COPIES_NUMBER=\"$COPIES_NUMBER\""
    } > "${config_file}"
}


if [ "$runtype" = "edit" ] ; then
    _edit_config
    nano "${config_file}"
    exit
fi


FILES=$(ls "$SQL_BACKUP_DIR"/"$DATABASE_NAME"_backup_*.sql.gz| sort)
FILE_COUNT=$(echo "$FILES" | wc -l)
OLDEST_FILE=$(echo "$FILES" | head -n 1)
BACKUP_FILE=${SQL_BACKUP_DIR}/"$DATABASE_NAME"_backup_`date +"%m-%d-%Y_%H-%M-%S"`.sql


if [ "$FILE_COUNT" -ge "$COPIES_NUMBER" ] ; then
    rm "$OLDEST_FILE" 
fi

mysqldump --login-path="$SQL_LOGIN_PATH" "$DATABASE_NAME" > "$BACKUP_FILE"

gzip "$BACKUP_FILE"
