#!/bin/bash
#finish package takes a directory input created by restructureforCompliance and creates derivative access copies, metadata documents, and a checksum file.
SCRIPTDIR=$(dirname "${0}")
. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};
_initialize_make

while [ "${*}" != "" ] ; do
#look for tree.xml
    PACKAGE="${1}"
    shift
    if [ -d "${PACKAGE}" ] ; then
        OUTPUTDIR="${PACKAGE}/metadata"
        _report -dt "running finishpackage on ${PACKAGE}" #the name of the package being verified

        #make a new temp tree
        TEMPTREE=$(_maketemp)
        tree -DaNXs --du --timefmt "%Y-%m-%dT%H:%M:%SZ" -I "tree.xml|.DS_Store" "${PACKAGE}" > "${TEMPTREE}"
        #if tree.xml exists, compare it to the specified xpath expressions of an AIP

        #check extension of first object file
        MOSTCOMMONEXTENSION="$(xmlstarlet sel -t -m "/tree/directory/directory[@name='objects']/file" -v "substring-after(@name, '.')" -n  "${TEMPTREE}"| sort | uniq -c | sort -n -r | head -n 1 | awk '{print $2}')"
        #if there is one object file and it uses a .wav extension, then run audio-specific tests 
        if [[ "${MOSTCOMMONEXTENSION}" = "wav" ]] ; then
            astataudit -v -c n -f n -x n -o ${PACKAGE}/metadata/depictions "${PACKAGE}/objects"
            "${SCRIPTDIR}/makederiv" -T waveform "${PACKAGE}"
            "${SCRIPTDIR}/makederiv" -T podcast "${PACKAGE}"
            "${SCRIPTDIR}/makederiv" -T mp3 "${PACKAGE}"
        elif [[ "${MOSTCOMMONEXTENSION}" = "tif" ]] ; then
            "${SCRIPTDIR}/makepdf" "${PACKAGE}"
        else
            makelossless "${PACKAGE}"
            "${SCRIPTDIR}/makederiv" -T broadcast "${PACKAGE}"
            "${SCRIPTDIR}/makederiv" -T youtube "${PACKAGE}"
            "${SCRIPTDIR}/makeframes" "${PACKAGE}"
            "${SCRIPTDIR}/makefingerprint" "${PACKAGE}"
            "${SCRIPTDIR}/makederiv" -T waveform "${PACKAGE}"
            "${SCRIPTDIR}/makederiv" -T podcast "${PACKAGE}"
            "${SCRIPTDIR}/makederiv" -T mp3 "${PACKAGE}"
        fi
        "${SCRIPTDIR}/makemetadata" "${PACKAGE}"
        "${SCRIPTDIR}/checksumpackage" "${PACKAGE}"
    fi
done
