#!/bin/bash
while [ "${*}" != "" ] ; do
    input="${1}"
    makelossless "${input}" && makebroadcast "${input}" && makeyoutube "${input}" && makemetadata "${input}" && checksumpackage "${input}"
    shift
done