#!/bin/bash
# left 2 stereo mix
version=1.1
unset dependencies
dependencies=(ffmbc)

scriptdir=$(dirname "$0")
. "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};

usage(){
    echo
    echo "$(basename $0) ${version}"
    echo "This application takes an input video file(s) and produces outputs that are map the left channel of the input to a stereo mix in the output."
    echo "Dependencies: ${dependencies[@]}"
    echo "Usage: $(basename $0) file1 [ file2 ...]"
    echo
    exit
}
[ "$#" = 0 ] && usage
check_dependencies "${dependencies[@]}"

cleanup(){
    log -a "Process aborted"
    exit 1
}

# local variables
suffix="_left2stereo"

trap cleanup SIGHUP SIGINT SIGTERM
log -b

while [ "$*" != "" ] ; do

    input_movie="$1"
    name=$(basename "$1")
    extension="${name#*.}"
    
    get_codectagstring
    unset ffmbc_opts
    ffmbc_opts+=(-vcodec copy -acodec pcm_s24le -ar 48000 -ac 2)
    ffmbc_opts+=(-map_audio_channel 0:1:0:0:1:0 -map_audio_channel 0:1:0:0:1:1)
    [ "${codec_tag_string}" = "mpeg" ] && extension="mxf"

    output_movie="${input_movie%.*}${suffix}.${extension}"
    if [ -f "${output_movie}" ] ; then
        report -wt "The intended output of $(basename $0) already exists. Skipping for now. Please delete ${output_movie} and rerun or figure out why you are trying to do this."
    else
        report -dt "Generating ${outputmovie} ..."
        ffmbc -i ${input_movie} ${ffmbc_opts[@]} ${output_movie}
        report -dt "$(basename $0) is done with ${name}."
    fi
    shift
done
log -e
