#!/bin/bash
# this script takes one argument which is a video file. It then rewraps it to make a new file.
version=1.1
unset dependencies
dependencies=(ffmbc)

scriptdir=$(dirname "${0}")
. "${scriptdir}/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};

usage(){
    echo
    echo "$(basename "${0}") ${version}"
    echo "This application takes an input video file(s) and produces outputs through re-multiplexing all tracks of the input into a new container."
    echo "Dependencies: ${dependencies[@]}"
    echo "Usage: $(basename "${0}") file1 [ file2 ...]"
    echo
    exit
}
[ "${#}" = 0 ] && usage
check_dependencies "${dependencies[@]}"

cleanup(){
    _log -a "Process aborted"
    exit 1
}

# local variables
suffix="_rewrap"

trap cleanup SIGHUP SIGINT SIGTERM
_log -b

while [ "${*}" != "" ] ; do

    sourcefile="${1}"
    name=$(basename "${sourcefile}")

    get_codectagstring
    unset ffmbc_opts
    ffmbc_opts+=(-vcodec copy -acodec copy)
    if [ "${codec_tag_string}" = "mpeg" ] ; then
        extension="mxf"
    else
        extension="mov"
    fi

    output_movie="${sourcefile%.*}${suffix}.${extension}"
    if [ -f "${output_movie}" ] ; then
        report -wt "The intended output of $(basename "${0}") already exists. Skipping for now. Please delete ${output_movie} and rerun or figure out why you are trying to do this."
    else
        report -dt "Generating ${outputmovie} ..."
        ffmbc -i ${sourcefile} ${ffmbc_opts[@]} ${output_movie}
        report -dt "$(basename "${0}") is done with ${name}."
    fi
    shift
done
_log -e
