#!/bin/bash
# ingestfile
# select an audiovisual file, package it, and transcode it

VERSION="1.0"
QUEUEFILE="${HOME}/Desktop/queue.txt"
SCRIPTDIR=$(dirname "${0}")
. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};
_initialize_make


AUDIODECISION_OPTIONS=("Default audio mapping [first audio track used for stereo output]" "" "Default audio mapping [first audio track used for stereo output]" "Only use left of the first audio track [for 21st Century]" "Only use right of the first audio track" "Only use the first track")
CROPDECISION_OPTIONS=("Do not crop" "" "Examine the video and auto-crop out black borders (slower)")
SLATE_OPTIONS=("No""""Yes")
FORMULA_OPTIONS=("none" "" "check interlacement" "tff" "bff" "hds" "sds")
CLEANUPDECISION_OPTIONS=("Leave source file where it is" "" "Remove source file after successful ingest")
PRIORITY_OPTIONS=("put in queue" "" "start now")

funcDirectory() {
    DIR_VAR_NAME="${1}"
    DIR_VAR_VALUE="${!1}"
    DIR_LABEL="${2}"
    if [[ -n "${DIR_VAR_VALUE}" ]] ;
    then DIR_DEFAULT="<default>${DIR_VAR_VALUE}</default>"
    fi
    cat << GTK_PART
    <vbox>
    	<text>
    		<label>"${DIR_LABEL}"</label>
    	</text>
    	<hbox>
      		<entry accept="directory" fs-entry="Select a Directory">
          		${DIR_DEFAULT}
       	  		<variable>${DIR_VAR_NAME}</variable>
      		</entry>
      		<button>
        		<input file stock="gtk-open"></input>
         		<variable>DIRBROWSE</variable>
        		<action type="fileselect">${DIR_VAR_NAME}</action>
      		</button>
    	</hbox>
    </vbox>
GTK_PART
}

funcEntry(){
  ENTRY_VAR_NAME="${1}"
  ENTRY_VAR_VALUE="${!1}"
  ENTRY_LABEL="${2}"
  if [[ -n "${ENTRY_VAR_VALUE}" ]] ;
  then ENTRY_DEFAULT="<default>${ENTRY_VAR_VALUE}</default>"
  fi
  cat << GTK_ENTRY
<vbox>
  <text wrap="true" width-chars="60" xalign="0">
    <label>${ENTRY_LABEL}</label>
  </text>
  <entry>
    <variable>${ENTRY_VAR_NAME}</variable>
    ${ENTRY_DEFAULT}
    </entry>
</vbox>
GTK_ENTRY
}

_get_index_of_value(){
  # run with function, value to look for as first argument, and array to look in as 2nd argument, such function as
  # _get_index_of_value "${VIDEO_INPUT_CHOICE}" "${VIDEO_INPUT_OPTIONS[@]}"
  VALUE="${1}"
  shift
  LIST=( "$@" )
  INDEX=0
  MATCH=""
  for ITEM in "${LIST[@]}" ; do
    if [[ "${VALUE}" = "${ITEM}" ]] ; then
      MATCH="$INDEX"
    fi
    (( ++INDEX ))
  done
    if [[ -n "${MATCH}" ]] ; then
      echo -n "${MATCH}"
    fi
}

_expand_list2items(){
  LIST=( "$@" )
    for i in "${LIST[@]}" ; do
      echo "<item>${i}</item>"
    done
}

funcCombo(){
    VARIABLE_NAME="${1}"
    WIDTH="${2}"
    LABEL="${3}"
    shift 3
    OPTION_LIST=("${@}")
    SELECTION="$(_get_index_of_value "${!VARIABLE_NAME}" "${OPTION_LIST[@]}")"
    LIST="$(_expand_list2items "${OPTION_LIST[@]}")"
    cat << GTK_COMBO
    <hbox>
      <text>
          <label>${LABEL}</label>
      </text>
      <comboboxtext allow-empty=\"false\" value-in-list=\"true\" button-sensitivity=\"1\" focus-on-click=\"false\" selection-mode=\"1\" selected-row=\"${SELECTION}\">
          <variable>${VARIABLE_NAME}</variable>
          ${LIST}
      </comboboxtext>
    </hbox>
GTK_COMBO
}



export MAIN_DIALOG=$(cat << MAIN_FORM
	<window title="ingestfile" resizable="false" window_position="1">
		<vbox>
			<text>
				<label>Ingest file options.</label>
			</text>
			<frame>
				$(funcEntry OPERATOR "Please enter your name")
				$(funcEntry MEDIAID "Please enter a unique MEDIA ID (capital letters, numbers, hyphens and underscores only).")
				$(funcDirectory INPUT "Select your file")
        $(funcCombo AUDIODECISION "100" "Select an audio strategy" ${AUDIODECISION_OPTIONS[@]})
        $(funcCombo CROPDECISION "100" "Select a cropping strategy:" ${CROPDECISION_OPTIONS[@]})
        $(funcCombo SLATE "100" "Do you want to create a service copy with a slate?" ${SLATE_OPTIONS[@]})
        $(funcEntry SERIESTITLE "If adding slate, please enter a series title:")
        $(funcEntry EPISODETITLE "If adding slate, please enter an episode title:")
        $(funcCombo FORMULA "100" "Select a formula for unusual cases (optional)" ${FORMULA_OPTIONS[@]})
        $(funcCombo CLEANUPDECISION "100" "Select a cleanup strategy" ${CLEANUPDECISION_OPTIONS[@]})
        $(funcCombo PRIORITY "100" "Would you like to put it in the queue or start now?" ${PRIORITY_OPTIONS[@]})
        $(funcEntry INTIME_ENTRY "Enter the in-point of the video (optional; in hh:mm:ss.s)")
        $(funcEntry OUTTIME_ENTRY "Enter the out-point of the video (optional; in hh:mm:ss.s")
			</frame>
      <hbox>
        <button ok></button>
        <button cancel></button>
      </hbox>
		</vbox>
	</window>
MAIN_FORM
)

echo "$MAIN_DIALOG" | mate
gtkdialog --program=MAIN_DIALOG 



