#!/bin/bash
# makedvd
# v 2.0 integrate with new microservice makederiv to streamline derivative creation
VERSION="2.0"
SCRIPTDIR=$(dirname $(which "${0}"))
. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};

_usage(){
    echo
    echo
    _report -d "makedvd is an alias for the updated function makederiv (options below)."
    _report -d "You can create a DVD with makederiv by typing: 'makederiv -T dvd [options] [input]'."
    _report -d "Or continue to use makedvd using the valid options below."
    "${SCRIPTDIR}/makederiv" -h
}
[ "${#}" = 0 ] && _usage
"${SCRIPTDIR}/makederiv" -T dvd "${@}"
