#!/bin/bash
#maketree creates an .xml from a directory structure
SCRIPTDIR=$(dirname $(which "${0}"))
. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};

while [ "${*}" != "" ] ; do
    # get context about the input
    PACKAGE="${1}"
    shift
    if [ -d "${PACKAGE}" ] ; then 
        OUTPUTDIR="${PACKAGE}/metadata"
        if [ -s "${OUTPUTDIR}/tree.xml" ] ; then
            _report -dt "directory tree already exists, skipping for ${PACKAGE}"
            continue
        fi
        _mkdir2 "${OUTPUTDIR}"
        "${SCRIPTDIR}/removeDSStore" "${PACKAGE}"
        tree -DaNXs --du --timefmt "%Y-%m-%dT%H:%M:%SZ" -I "tree.xml" "${PACKAGE}" > "${OUTPUTDIR}/tree.xml"
    else
        _report -dt "${PACKAGE} is not a directory, can't make a tree!"
    fi
done

