#!/bin/bash
#maketree creates an .xml from a directory structure
SCRIPTDIR=$(dirname $(which "${0}"))
. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};

while [ "${*}" != "" ] ; do
    # get context about the input
    INPUT="${1}"
    shift
    if [ -d "${INPUT}" ] ; then 
        OUTPUTDIR="${INPUT}/metadata"
        if [ -s "${OUTPUTDIR}/tree.xml" ] ; then
            _report -dt "directory tree already exists, skipping for ${INPUT}"
            continue
        fi
        _mkdir2 "${OUTPUTDIR}"
        tree -DaNXs --du --timefmt "%Y-%m-%dT%H:%M:%SZ" "${INPUT}" > "${OUTPUTDIR}/tree.xml"
    else
        _report -dt "${INPUT} is not a directory, can't make a tree!"
    fi
done

