#!/bin/bash
# makeyoutube, makes a file appropriate for uploading to youtube
SCRIPTDIR=$(dirname $(which "${0}"))
. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};
SUFFIX="_signature"
EXTENSION="xml"
RELATIVEPATH="metadata"


while [ "${*}" != "" ] ; do
    # get context about the input
    INPUT="${1}"
    shift
    if [ -z "${OUTPUTDIR_FORCED}" ] ; then
        [ -d "${INPUT}" ] && { OUTPUTDIR="$INPUT/metadata/${RELATIVEPATH}" && FINGERDIR="${INPUT}/metadata/fingerprints" ;};
        [ -f "${INPUT}" ] && { OUTPUTDIR=$(dirname "${INPUT}")"/${RELATIVEPATH}" && FINGERDIR="$(dirname "${INPUT}")/fingerprints" ;};
        [ ! "${OUTPUTDIR}" ] && { OUTPUTDIR="${INPUT}/metadata/${RELATIVEPATH}" && FINGERDIR="${INPUT}/metadata/fingerprints" ;};
    else
        OUTPUTDIR="${OUTPUTDIR_FORCED}"
        FINGERDIR="${OUTPUTDIR}/metadata/fingerprints"
    fi
    _unset_variables
    _find_input "${INPUT}"
    MEDIAID=$(basename "${INPUT}" | cut -d. -f1)

#    _set_up_output
    if [ "${FINGERDIR}" != "" ] ; then
        _mkdir2 "${FINGERDIR}"
    fi
    SIGNATURE="${MEDIAID}""${SUFFIX}"."${EXTENSION}"
    _run_critical_event ~/ffmpeg/ffmpeg "${FFMPEGINPUT[@]}" -vf signature=format=xml:filename="${FINGERDIR}/${SIGNATURE}" -map 0:v -f null -
    FINGERPRINT_XML="${FINGERDIR}/${SIGNATURE}"
    
    _fingerprint_to_db
    _report_to_db
    _eventoutcome_update
done