#!/bin/bash
# makeresourcespace, makes a file appropriate for uploading to resourcespace, is used in a local script, queryresourcespace
# v 2.0 integrate with new microservice makederiv to streamline derivative creation
VERSION="2.0"
SCRIPTDIR=$(dirname $(which "${0}"))
. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};

_usage(){
    echo
    echo
    _report -d "makeresourcespace is an alias for the updated function makederiv (options below)."
    _report -d "You can create a derivative file for ResourceSpace with makederiv by typing: 'makederiv -T resourcespace [options] [input]'."
    _report -d "Or continue to use makeresourcespace using the valid options below."
    "${SCRIPTDIR}/makederiv" -h
}
[ "${#}" = 0 ] && _usage
"${SCRIPTDIR}/makederiv" -T resourcespace "${@}"
