#!/bin/bash
# makepodcast, makes a file appropriate for podcasting
VERSION="1.0"
SCRIPTDIR=$(dirname $(which "${0}"))
. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};
DEPENDENCIES=(ffmpeg ffprobe)
_initialize_make
SUFFIX="_podcast"
EXTENSION="mov"
RELATIVEPATH="access/podcast"

_usage(){
    echo
    echo "$(basename "${0}") ${VERSION}"
    echo "This application will create a QuickTime file suitable for podcasting from a video file or package input with the following options."
    echo "Dependencies: ${DEPENDENCIES[@]}"
    echo "Usage: $(basename ${0}) [ -d /path/to/deliver/to/ ] fileorpackage1 [ fileorpackage2 ...]"
    echo "  -d directory ( directory to deliver the resulting file to )"
    echo "  -o directory ( directory to write the resulting file to )"
    echo "  -n (dry-run mode, show the commands that would be run but don't do anything)"
    echo "  -e emailaddress ( send an email about the delivery, only valid if -d is used )"
    echo "  -E emailaddress ( send an email about process outcome )"
    echo "  -h ( display this help )"
    echo
    exit
}
[ "${#}" = 0 ] && _usage

user_input="${*}"
# command-line options to set mediaid and original variables
OPTIND=1
while getopts ":o:d:e:E:nh" OPT ; do
    case "${OPT}" in
        o) OUTPUTDIR_FORCED="${OPTARG}" && _check_outputdir_forced ;;
        d) DELIVERDIR="${OPTARG}" && _check_deliverdir ;;
        e) EMAILADDRESS_DELIVERY="${OPTARG}" && check_emailaddress "${EMAILADDRESS_DELIVERY}" ;;
        E) EMAILADDRESS_OUTCOME="${OPTARG}" && check_emailaddress "${EMAILADDRESS_OUTCOME}" ;;
        n) DRYRUN=true;;
        h) _usage ;;
        *) echo "bad option -${OPTARG}" ; _usage ;;
        :) echo "Option -${OPTARG} requires an argument" ; _writeerrorlog "makepodcast" "The option selected required an argument and none was provided. The script had to exit." ; exit 1 ;;
    esac
done
shift $(( ${OPTIND} - 1 ))

while [ "${*}" != "" ] ; do
    # get context about the input
    INPUT="${1}"
    shift
    if [ -z "${OUTPUTDIR_FORCED}" ] ; then
        [ -d "${INPUT}" ] && { OUTPUTDIR="$INPUT/objects/${RELATIVEPATH}" && LOGDIR="${INPUT}/metadata/logs" ;};
        [ -f "${INPUT}" ] && { OUTPUTDIR=$(dirname "${INPUT}")"/${RELATIVEPATH}" && LOGDIR="$(dirname "${INPUT}")/${RELATIVEPATH}/logs" ;};
        [ ! "${OUTPUTDIR}" ] && { OUTPUTDIR="${INPUT}/objects/${RELATIVEPATH}" && LOGDIR="${INPUT}/metadata/logs" ;};
    else
        OUTPUTDIR="${OUTPUTDIR_FORCED}"
        LOGDIR="${OUTPUTDIR}/logs"
    fi
    _unset_variables
    _find_input "${INPUT}"
    MEDIAID=$(basename "${INPUT}" | cut -d. -f1)
    _report_to_db

    _set_up_output

    # encoding options
    _get_codectagstring "${SOURCEFILE}"
    _get_videostreamcount "${SOURCEFILE}"
    _get_audiostreamcount "${SOURCEFILE}"
    INPUTOPTIONS+=(-nostdin)
    if [[ "${VIDEOSTREAMCOUNT}" > 0 ]] ; then
        if [[ "${CODEC_TAG_STRING}" == "mjp2" ]] ; then
             INPUTOPTIONS+=(-vcodec libopenjpeg)
        fi
        MIDDLEOPTIONS+=(-movflags faststart)
        MIDDLEOPTIONS+=(-pix_fmt yuv420p)
        MIDDLEOPTIONS+=(-c:v libx264)
        MIDDLEOPTIONS+=(-b:v 1500k)
        MIDDLEOPTIONS+=(-maxrate:v 3000k)
        MIDDLEOPTIONS+=(-minrate:v 375k)
        MIDDLEOPTIONS+=(-bufsize:v 6000k)
        _add_video_filter "yadif"
        _add_video_filter "scale=640:trunc(ow/dar/2)*2:interl=1"
    fi
    if [[ "${AUDIOSTREAMCOUNT}" > 0 ]] ; then
        MIDDLEOPTIONS+=(-c:a aac -strict -2)
        MIDDLEOPTIONS+=(-b:a 96k)
        _get_audio_mapping "${SOURCEFILE}"
        MIDDLEOPTIONS+=("${AUDIOMAPPING_FFMPEG[@]}")
    fi
    _prep_ffmpeg_log
    if [ "${CONCATSOURCE}" != "" ] ; then
        FFMPEGINPUT="${CONCATSOURCE}"
    fi

    _filter_to_middle_option

    _run_critical_event ffmpeg "${INPUTOPTIONS[@]}" "${FFMPEGINPUT[@]}" "${MIDDLEOPTIONS[@]}" "${OUTPUT}"
    echo
    _summarize_make
    _deliver_output "${MAKEYOUTUBE_DELIVERY_EMAIL_TO}"
    _log -e
done
