#!/bin/bash
#this script creates colorbars, a slate, and adds 30 seconds of black at the end of a video file input

cowsay "MediaID?"
echo -n ":: "
read MEDIAID

cowsay -t "Series Title?"
echo -n ":: "
read SERIESTITLE

cowsay -s "Episode Title?"
echo -n ":: "
read EPISODETITLE

COLORBARS_SECS=60
SLATE_SECS=20
COUNTDOWN_SECS=8.2
BLACK_SECS=1.8

echo "${MEDIAID}" > /tmp/slate_mediaid.txt
echo "${SERIESTITLE}" > /tmp/slate_series.txt
echo "${EPISODETITLE}" > /tmp/slate_episode.txt

echo "AUDIO:
Ch. 1: Stereo L
Ch. 2: Stereo R
Ch. 3: Unused
Ch. 4: Unused" > /tmp/slate_audio.txt

fontfile="/System/Library/Fonts/HelveticaNeue.dfont"
fontenable="enable=gte(t\,${COLORBARS_SECS})*lt(t\,${COLORBARS_SECS}+${SLATE_SECS})"

ffmpeg \
    -f lavfi -i "smptehdbars=s=1920x1080:r=30000/1001:sar=16/9:d=${COLORBARS_SECS}" \
    -f lavfi -i "aevalsrc=0.1*sin(1000*2*PI*t):d=${COLORBARS_SECS}:s=48000:c=2" \
    -f lavfi -i "color=c=BlueViolet:s=1920x1080:r=30000/1001:sar=16/9:d=${COUNTDOWN_SECS},geq=r='X/W*r(X,Y)':g='(1-X/W)*g(X,Y)':b='(H-Y)/H*b(X,Y)'" \
    -f lavfi -i "aevalsrc=0:d=${SLATE_SECS}:s=48000:c=2" \
    -f lavfi -i "color=black:s=1920x1080:r=30000/1001:sar=16/9:d=${COUNTDOWN_SECS}" \
    -f lavfi -i "sine=r=48000:frequency=1:beep_factor=400:duration=${COUNTDOWN_SECS}"\
    -f lavfi -i "color=black:s=1920x1080:r=30000/1001:sar=16/9:d=${BLACK_SECS}" \
    -f lavfi -i "aevalsrc=0:d=${BLACK_SECS}:s=48000:c=2" \
    -filter_complex "[0:v:0][1:a:0][2:v:0][3:a:0][4:v:0][5:a:0][6:v:0][7:a:0]concat=n=4:v=1:a=1[v][a];\
    [v]\
    drawtext=fontsize=32:fontfile=${fontfile}:fontcolor=white:${fontenable}:x=388:y=158:textfile=/tmp/slate_mediaid.txt,\
    drawtext=fontsize=110:fontfile=${fontfile}:fontcolor=white:${fontenable}:x=388:y=370:textfile=/tmp/slate_series.txt,\
    drawtext=fontsize=50:fontfile=${fontfile}:fontcolor=white:${fontenable}:x=388:y=460:textfile=/tmp/slate_episode.txt,\
    drawtext=fontsize=32:fontfile=${fontfile}:fontcolor=white:${fontenable}:x=388:y=793:text='VIDEO',\
    drawtext=fontsize=32:fontfile=${fontfile}:fontcolor=white:${fontenable}:x=388:y=831:text='1080i',\
    drawtext=fontsize=32:fontfile=${fontfile}:fontcolor=white:${fontenable}:x=388:y=869:text='59.94DF',\
    drawtext=fontsize=32:fontfile=${fontfile}:fontcolor=white:${fontenable}:x=790:y=793:text='AUDIO',\
    drawtext=fontsize=32:fontfile=${fontfile}:fontcolor=white:${fontenable}:x=790:y=831:text='Ch 1\: Stereo L',\
    drawtext=fontsize=32:fontfile=${fontfile}:fontcolor=white:${fontenable}:x=790:y=869:text='Ch 2\: Stereo R',\
    drawtext=fontsize=32:fontfile=${fontfile}:fontcolor=white:${fontenable}:x=790:y=908:text='Ch 3\: Mono Mix',\
    drawtext=fontsize=32:fontfile=${fontfile}:fontcolor=white:${fontenable}:x=790:y=947:text='Ch 4\: Mono Mix',\
    drawtext=fontsize=32:fontfile=${fontfile}:fontcolor=white:${fontenable}:x=1151:y=908:text='Duration',\
    drawtext=fontsize=420:fontfile=${fontfile}:fontcolor=white:enable=gte(t\,${COLORBARS_SECS}+${SLATE_SECS})*lt(t\,${COLORBARS_SECS}+${SLATE_SECS}+${COUNTDOWN_SECS}):x=(w-text_w)/2:y=(h-text_h-line_h)/2:text='%{eif\:${COLORBARS_SECS}+${SLATE_SECS}+11-t\:d}',\
    scale=size=hd1080,format=yuv422p,setsar=1/1,setdar=16/9,fps=fps=ntsc[v1];[a]asplit[a1][a2];[a1]aformat=channel_layouts=stereo[stereo1];[a2]aformat=channel_layouts=mono,asplit[mono1][mono2]" \
    -map '[v1]' -map "[stereo1]" -map "[mono1]" -map "[mono2]" -shortest \
    -r ntsc -c:v mpeg2video -intra_vlc 1 -non_linear_quant 1 -qmin 1 -dc 10 -lmin QP2LAMBDA -ps 1 -flags +ildct+ilme -pix_fmt yuv422p -metadata:s:v:0 "timecode=00:58:30;00" -s 1920x1080 -vtag xd5b -aspect 16:9 -q:v 1 -qmax 8 -g 15 -bf 2 -b:v 50M -maxrate:v 50M -minrate:v 50M -bufsize 17825792 -rc_init_occupancy 17825792 -acodec pcm_s24be -ar 48k -ac 2 "${HOME}/DeskTop/${MEDIAID}_SLATE.mov"

cowsay "I left ${MEDIAID}_SLATE.mov on your Desktop, peace"
