#!/bin/bash
# makewaveform, makes a visual representation of the primary audio of the input
# v 2.0 integrate with new microservice makederiv to streamline derivative creation
VERSION="1.0"
SCRIPTDIR=$(dirname $(which "${0}"))
. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};

_usage(){
    echo
    echo
    _report -d "makewaveform is an alias for the updated function makederiv (options below)."
    _report -d "You can create a a visual representation of the primary audio of the input with makederiv by typing: 'makederiv -T waveform [options] [input]'."
    _report -d "Or continue to use makewaveform using the valid options below."
    "${SCRIPTDIR}/makederiv" -h
}
[ "${#}" = 0 ] && _usage
"${SCRIPTDIR}/makederiv" -T waveform "${@}"
