#!/bin/bash
#microservice for moving files during migration, uses rsync to move files and write log, have to format to have source and target locations 
SCRIPTDIR=$(dirname $(which "${0}"))
. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};

_usage(){
    echo "This script moves files from one location to another."
    echo "  -o directory ( directory to write the resulting file to )"
    echo "the structure of the script is as follows: migrateaip -o ${TARGET} ${INPUT}"
}

OPTIND=1
while getopts ":o:l:r" OPT ; do
    case "${OPT}" in
        o) OUTPUTDIR_FORCED="${OPTARG}" ;;
        r) REMOVESOURCEFILES="Y" ;;
        l) LOGFILE="${OPTARG}" ;;
        *) echo "bad option -${OPTARG}" ; usage ;;
        :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
    esac
done
shift $(( ${OPTIND} - 1 ))

TARGET="${OUTPUTDIR_FORCED}/"
DATE=$(_get_iso8601_c)

while [ "${*}" != "" ] ; do
    INPUT="${1}"
    echo "The input is: ${INPUT}"
    echo "The target is: ${TARGET}"
    echo "HEY! The log file is ${LOGFILE}"
    shift
    if [ -z "${LOGFILE}" ] ; then
        LOGFILE="${HOME}/migrate.log"
        echo "HEY! The log file is ${LOGFILE}"
    fi
    if [ "${REMOVESOURCEFILES}" == "Y" ] ; then
        EXTRAOUTPUTS+=(--remove-source-files)
    fi
    rsync -rtvc "${EXTRAOUTPUTS[@]}" --log-file="${LOGFILE}" --log-file-format="[%C] ${DATE} '%f' %l '${TARGET}'" "${INPUT}" "${TARGET}" 
done
