#!/bin/bash
#microservice for moving files during migration, uses rsync to move files and write log, have to format to have source and target locations 
SCRIPTDIR=$(dirname $(which "${0}"))
. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};

_usage(){
    echo "This script moves files from one location to another."
    echo "  -o directory ( directory to write the resulting file to )"
    echo "the structure of the script is as follows: migrateaip -o ${TARGET} ${INPUT}"
}

OPTIND=1
while getopts ":o:" OPT ; do
    case "${OPT}" in
        o) OUTPUTDIR_FORCED="${OPTARG}" ;;
        *) echo "bad option -${OPTARG}" ; usage ;;
        :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
    esac
done
shift $(( ${OPTIND} - 1 ))

TARGET="${OUTPUTDIR_FORCED}"
DATE=$(_get_iso8601_c)

while [ "${*}" != "" ] ; do
    INPUT="${1}"
    echo "The input is: ${INPUT}"
    echo "The target is: ${TARGET}"
    shift
    rsync -rtvc --log-file="${HOME}/migrateaip.log" --log-file-format="(%C) '%f' %l '${TARGET}' ${DATE}" "${INPUT}" "${TARGET}"
done