#!/bin/sh
# help documentation
# This script presents an index of microservices along with their options and definitions.

echo "

barcode_interpret

	Arguments:		one or many scanned interleaved 2/5 barcode values
	Description:		The script will translate the scanned barcode into human a
					readable numerical value and retrieve the associated identifiers.


blackatend

	Arguments: 		one or many video files.
	Example:		blackatend /path/to/file1.mov /path/to/file2.mov
	Description:		The script will decode the first and last few seconds of the file
				and report on the number of black frames at each end.


checksumpackage
 
	Arguments: 		one or many Archive Information Packages (AIP)
	Example:		checksumpackage /path/to/package1 /path/to/package2
	Description:		The script will use md5deep to produce a checksum.md5 file for
				AIPs to help facilitate file integrity checks during long
				term digital storage.


fix_left2stereo
	
	Arguments:		one video file with .mxf or .mov extension
	Example:		fix_left2stereo /path/to/file1.mxf /path/to/file1.mov
	Description:		The script will adjust stereo audio to the left channel.


fix_rewrap
	
	Arguments:		one video file with .mxf or .mov extension
	Example:		fix_rewrap /path/to/file1.mxf /path/to/file1.mov
	Description:		The script will change the wrapper of a video file.


fix_volume

	Arguments:		one video file with .mxf or .mov extension
	Example:		fix_volume /path/to/file1.mxf /path/to/file1.mov
	Description			The script will evaluate the audio of a video file to determine 
					the difference and adjust as needed. 


ingestfile

	Arguments:		one or many audiovisual files
	Example:		ingestfile /path/to/file1.mov /path/to/file2.mov
	Description:		The script will package, transcode, and ingest an audiovisual file. This script
					makes use of several functions described in the mmfunctions script.


install

	Arguments:
	Example:
	Description:

makebroadcast

	Arguments:		one or many video files.
	Example:		makebroadcast /path/to/file1.mov /path/to/file2.mov
	Description:			The script will create a broadcast version of a video file. Version 1.2 
					reverts the video file to .mov and ffmbc.


makedvd
	
	Arguments:		one or many video files.
	Example:		makedvd /path/to/file1.mov /path/to/file2.mov
	Description:			The script will create and label a dvd version of a video file.


makemetadata

	Arguments:		
	Example:		
	Description:


makepodcast

	Arguments:		one or many video files.
	Example:		makepodcast /path/to/file1.mov /path/to/file2.mov
	Description:			The script will create a video file suitable for podcast.


makeyoutube

	Arguments: 		one or many video files.
	Example:		makeyoutube /path/to/file1.mov /path/to/file2.mov
	Description:		The script will create a video file suitable for youtube upload.


quickcompare

	Arguments:		two files.
	Description:		The script will quickly compare two files.


removeDSStore

	Arguments: 		one or many Archive Information Packages (AIP)
	Example:		removeDSStore /path/to/package1 /path/to/package2
	Description:		The script will remove .DS_Store files from
				 AIPs because they are annoying.

uploadomneon

	Arguments:		one or many video files.
	Example:		uploadomneon /path/to/file1.mov /path/to/file2.mov
	Description:		The script will prepare and upload a video file to the Omneon.


xdcamingest

	Arguments:		none. The script is only run interactively.
	Description:		The script will ingest an xdcam disc, make a package, and deliver select files.	
"

