#!/bin/bash

scriptdir=`dirname "$0"`
. "$scriptdir/mmvariables"
. "$scriptdir/mmfunctions"

cleanup(){
	log -a "Process aborted"
	exit 1
}

trap cleanup SIGHUP SIGINT SIGTERM
log -b

ask_operator

ask_mediaid

if [ -d "$mediaid" ] ; then
	report -wdt "It looks like this $mediaid was already scanned. If you want to overwrite the existing one please delete $mediaid first and then try again."
exit
fi

free_space 5 "$outputdir_paper"
  
origdir="$outputdir_paper/$mediaid/objects"
submissionMetadataDir="$outputdir_paper/$mediaid/metadata/submissionDocumentation"
logdir="$outputdir_paper/$mediaid/logs"
  
mkdir -p "$origdir"
mkdir -p "$submissionMetadataDir"
mkdir -p "$logdir"
  
start=`date -u "+%Y%m%dT%H%M%SZ"`

command="fscanx  --adf --rgb --bits 8 --resolution 600 --paper-width 10200 --paper-height 13200 --rotate-n-n --left 0 --width 10200 --top 0 --height 13200 --double-feed n --tiff --no-jpeg --images-per-file 1 --compress zlib '$origdir/${mediaid}_.tif'"
exec &> "$submissionMetadataDir/fscanx_process.txt"
eval "$command"
first=`find "$origdir" -type f -mindepth 1 -maxdepth 1 ! -name ".*" -exec ls -1rt '{}' \; | head -n 1`
last=`ls -1t "$origdir" | head -n 1`
open -a /Applications/Preview.app/ "$first" "$origdir/$last"
end=`date -u "+%Y%m%dT%H%M%SZ"`
system_data=`system_profiler SPHardwareDataType`
#These retrieved the right info on the Mac I'm using, but I don't know how standard the output is
serial_number=`echo "$system_data" | grep "Serial Number" | awk '{ print $4 }'`
model=`echo "$system_data" | grep "Model Identifier" | awk '{ print $3; }'`
os=`system_profiler SPSoftwareDataType | grep "System Version" | awk '{ print substr($0, index($0,$3)); }'`
echo "datetime_start: ${start}" >> "$submissionMetadataDir/operation_process.txt"
echo "datetime_end: ${end}" >> "$submissionMetadataDir/operation_process.txt"
echo "serial number: ${serial_number}" >> "$submissionMetadataDir/operation_process.txt"
echo "model id: ${model}" >> "$submissionMetadataDir/operation_process.txt"
echo "os: ${os}" >> "$submissionMetadataDir/operation_process.txt"
echo "identifier: ${mediaid}" >> "$submissionMetadataDir/operation_process.txt"
echo "operator: ${op}" >> "$submissionMetadataDir/operation_process.txt"
echo "command: ${command}"  >> "$submissionMetadataDir/operation_process.txt"

echo done scanning "$mediaid"

log -e
