#!/bin/bash
# @author Dave Rice

scriptdir=$(dirname "$0")
. "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};

cleanup(){
    _log -a "Process aborted"
    exit 1
}

trap cleanup SIGHUP SIGINT SIGTERM
_log -b

while [ "$*" != "" ] ; do
    target=$1
    if [ -d "$target" ]; then
        find "$target" -name '.DS_Store' -type f -delete
    fi
    shift
done
_log -e
