#!/bin/bash
# This file is part of Archivematica.
#
# Copyright 2010-2013 Artefactual Systems Inc. <http://artefactual.com>
#
# Archivematica is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Archivematica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Archivematica.  If not, see <http://www.gnu.org/licenses/>.

# @package Archivematica
# @subpackage SIPCreationTools
# @author Joseph Perry <joseph@artefactual.com>
# @version svn: $Id: 9e1ecac84215aaafd740d15eb0cbdc4c17b7fa1e $

SCRIPTDIR=$(dirname $(which "${0}"))
. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};

TARGET="${1}"

if [ -d "${TARGET}" ]; then
    mkdir "${TARGET}/objects"
    mv $(find "${TARGET}" -mindepth 1 -maxdepth 1 ! -name "objects") "${TARGET}objects/"
    mkdir -p "${TARGET}/metadata/submissionDocumentation"
    mkdir -p "${TARGET}/metadata/submissionDocumentation/fileMeta"
    mkdir -p "${TARGET}/metadata/submissionDocumentation/logs"
elif [ -f "${TARGET}" -a ! -d "$(dirname "${TARGET}")/$(basename "${TARGET%.*}")" ]; then
    _report -qn "Enter the Media ID: "
    read MEDIAID
    mkdir -p "$(dirname "${TARGET}")/${MEDIAID}/objects"
    mv "${TARGET}" "$(dirname "${TARGET}")/${MEDIAID}/objects/"
    mkdir -p "$(dirname "${TARGET}")/${MEDIAID}/metadata/submissionDocumentation/fileMeta"
    LOGDIR="$(dirname "${TARGET}")/${MEDIAID}/metadata/submissionDocumentation/logs"
    mkdir -p "${LOGDIR}"
    _ask_intime
    INGESTLOG="${LOGDIR}/capture.log"
    if [ "${INTIME}" ] ; then
        _writeingestlog "intime" "${INTIME}"
    fi
    _ask_outtime
    if [ "${OUTTIME}" ] ; then
        _writeingestlog "outtime" "${OUTTIME}"
    fi
else
    echo Error: Needs SIP directory or file as argument 1>&2
    exit 1
fi
