#!/bin/bash
# This file is part of Archivematica.
#
# Copyright 2010-2013 Artefactual Systems Inc. <http://artefactual.com>
#
# Archivematica is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Archivematica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Archivematica.  If not, see <http://www.gnu.org/licenses/>.

# @package Archivematica
# @subpackage SIPCreationTools
# @author Joseph Perry <joseph@artefactual.com>
# @version svn: $Id: 9e1ecac84215aaafd740d15eb0cbdc4c17b7fa1e $

scriptdir=$(dirname $(which "${0}"))
. "${scriptdir}/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};

target="${1}"

if [ -d "${target}" ]; then
    mkdir "${target}/objects"
    mv $(find "${target}" -mindepth 1 -maxdepth 1 ! -name "objects") "${target}objects/"
    mkdir -p "${target}/metadata/submissionDocumentation"
    mkdir -p "${target}/metadata/submissionDocumentation/fileMeta"
    mkdir -p "${target}/metadata/submissionDocumentation/logs"
elif [ -f "${target}" -a ! -d "$(dirname "${target}")/$(basename "${target%.*}")" ]; then
    report -qn "Enter the Media ID: "
    read mediaid
    mkdir -p "$(dirname "${target}")/${mediaid}/objects"
    mv "$target" "$(dirname "${target}")/${mediaid}/objects/"
    mkdir -p "$(dirname "${target}")/${mediaid}/metadata/submissionDocumentation/fileMeta"
    logdir="$(dirname "${target}")/${mediaid}/metadata/submissionDocumentation/logs"
    mkdir -p "${logdir}"
    _ask_intime
    ingestlog="${logdir}/capture.log"
    if [ "${intime}" ] ; then
        _writeingestlog "intime" "${intime}"
    fi
    _ask_outtime
    if [ "${outtime}" ] ; then
        _writeingestlog "outtime" "${outtime}"
    fi
else
    echo Error: Needs SIP directory or file as argument 1>&2
    exit 1
fi
