#!/bin/bash
# uploadomneon
# upload to omneon
requireconfig="Y"

version="1.0"

scriptdir=$(dirname "$0")
. "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};

usage(){
    echo
    echo "$(basename $0) ${version}"
    echo "This application will upload file(s) to a server via rsync in sequential order. Options are specified via 'mmconfig'."
    echo
    echo "Settings:"
    echo "OMNEONIP=${OMNEONIP}"
    echo "OMNEONPATH=${OMNEONPATH}"
    echo "TMPDIR=${TMPDIR}"
    echo "Usage: $(basename $0) file1 [ file2 ...]"
    echo "  -h ( display this help )"
    echo
    exit
}
[ "$#" = 0 ] && usage

cleanup(){
    log -a "Process aborted"
    exit 1
}

trap cleanup SIGHUP SIGINT SIGTERM
log -b

# command-line options to set mediaid and original variables
OPTIND=1
while getopts ":h" opt; do
    case "$opt" in
        h) usage ;;
        *) echo "Invalid option: -$OPTARG" ; exit 1 ;;
        :) echo "Option -$OPTARG requires an argument" ; exit 1 ;;
    esac
done
shift $(( ${OPTIND} - 1 ))

[ ! -d "$TMPDIR" ] && { echo "The temporary directory must be set and be available. Run 'mmconfig'." ; exit 1 ;};
[ ! -d "$OMNEONIP"] && { echo "The Omneon IP must be set. Run 'mmconfig'." ; exit 1 ;};
[ ! -d "$OMNEONPATH"] && { echo "The Omneon Path must be set. Run 'mmconfig'." ; exit 1 ;};

while [ "$*" != "" ] ; do

sourcefile="$1"
removetmp="n"
filename=$(basename "$sourcefile")

log -b

status=$(ftp -a "$OMNEONIP" <<END_SCRIPT
binary
ls "${OMNEONPATH}/${filename}"
exit
END_SCRIPT)
if [ "$status" = "Name not found." ] ; then
report "The file named $filename is not currently on the omneon, proceeding..."

if echo "$sourcefile" | grep -q "/Volumes/[AB][0-9]\{5\}" ; then
    report -dt "The file ${filename} is coming from an LTO tape. It will first move the file to ${TMPDIR} and then upload to the omneon."
    rsync -rtv --progress "$sourcefile" "${TMPDIR}/"
    uploadfile="${TMPDIR}/${filename}"
    removetmp="y"
else
    uploadfile="$sourcefile"
fi

report -dt "Starting to ftp $filename to the Omneon..."
ftp -a "$OMNEONIP" <<END_SCRIPT
binary
put "$uploadfile" "${OMNEONPATH}/${filename}"
exit
END_SCRIPT
upload_err="${?}"
report -wt "ftp exited with code ${upload_err}"
report -dt "${filename} is uploaded to the omneon"
[ "$upload_err" = "0" ] && [ "$removetmp" = "y" ] && rm "${TMPDIR}/${filename}"
else
size=$(echo "$status" | grep "$filename" | awk '{print $5}')
size_g=$(echo "scale=3; $size / 1073741824" | bc)
report -wt "$filename is already on the omneon as a $size_g gigabyte file."
fi
shift
done
log -e
