#!/bin/bash
#verifypackage creates checks the validity of files created with makebroadcast 
SCRIPTDIR=$(dirname "${0}")
. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};
unset DEPENDENCIES
DEPENDENCIES=(mediaconch xmlstarlet xml "${SCRIPTDIR}/makebroadcast_policies.xml")

#input the package
while [ "${*}" != "" ] ; do
#verify makebroadcast file
    PACKAGE="${1}"
    MEDIAID=$(basename "${PACKAGE}")
    shift
mediaconch -fx -p "${SCRIPTDIR}/makebroadcast_policies.xml" "${PACKAGE}/objects/service/${MEDIAID}.mov" | xml sel -N mc="https://mediaarea.net/mediaconch" -t -v mc:MediaConch/mc:media/mc:policy/@outcome -o " " -v mc:MediaConch/mc:media/@ref -n

done